version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: device_container
    command: --default-authentication-plugin=mysql_native_password

    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3314:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: